// ============================================
// BOT RECIPES LOADER
// Telegram bot se add hui recipes automatically
// yahan se load hoti hain aur app mein merge ho jaati hain
// ============================================

// This file is auto-generated by the Telegram bot.
// DO NOT EDIT MANUALLY.
// Location: bot_recipes.json → loaded here as JS variable

// Initialize as empty — actual data will be fetched from bot_recipes.json
window.botRecipes = [];

// Fetch bot recipes from bot_recipes.json (works on local server)
(async function loadBotRecipes() {
    try {
        const res = await fetch('bot_recipes.json');
        if (!res.ok) return; // file doesn't exist yet, that's fine
        const recipes = await res.json();
        if (Array.isArray(recipes) && recipes.length > 0) {
            window.botRecipes = recipes;
            console.log(`✅ Bot recipes loaded: ${recipes.length}`);
            // Dispatch event so app.js can react
            window.dispatchEvent(new CustomEvent('botRecipesLoaded', { detail: recipes }));
        }
    } catch (e) {
        // Normal — file doesn't exist yet if no bot recipes added
        console.log('ℹ️ No bot recipes yet (bot_recipes.json not found)');
    }
})();
